language: java
install: true

os:
  - linux

jdk:
  - openjdk17
  - oraclejdk17

script:
  - ./gradlew build --info
  - ./gradlew jacocoTestReport generateJacocoBadge

after_success:
  - bash <(curl -s https://codecov.io/bash) -t ab251073-1ba1-4600-a84c-dd3f71465f4f
