server:
  port: 40180

# This parameters show where EaseCI Core should searching for .run.yml file
# required when we want to restart application with just existing workspace.
# Application on startup will search for .run.yml file, first on current dir
# where .jar file with EaseCI is placed.
path:
  run:
    filename: .run.yml
    linux:
      - /opt
      - /tmp