extension:
  - item:
    interface: io.easeci.extension.bootstrap.OnStartup
    - plugin:
        uuid: 4593a486-776b-11ea-bc55-0242ac130003
        name: welcome-logo
        version: 0.0.1
        enabled: true
    - plugin:
        uuid: 919f57ca-776c-11ea-bc55-0242ac130003
        name: welcome-logo
        version: 0.0.2
        enabled: false
